"""report add date

Revision ID: 19215a5c5cab
Revises: 36b15b5a5f9b
Create Date: 2018-08-07 17:42:35.690961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19215a5c5cab'
down_revision = '36b15b5a5f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chandao_session_id')
    op.drop_column('user', 'chandao_za')
    op.add_column('weekly_report', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('weekly_report', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_report', 'start_date')
    op.drop_column('weekly_report', 'end_date')
    op.add_column('user', sa.Column('chandao_za', sa.VARCHAR(length=40), nullable=True))
    op.add_column('user', sa.Column('chandao_session_id', sa.VARCHAR(length=40), nullable=True))
    # ### end Alembic commands ###
