"""update weekly report model

Revision ID: 36b15b5a5f9b
Revises: f65675e913e6
Create Date: 2018-08-07 14:44:24.762753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b15b5a5f9b'
down_revision = 'f65675e913e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chandao_session_id')
    op.drop_column('user', 'chandao_za')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chandao_za', sa.VARCHAR(length=40), nullable=True))
    op.add_column('user', sa.Column('chandao_session_id', sa.VARCHAR(length=40), nullable=True))
    # ### end Alembic commands ###
