"""next week todo

Revision ID: 4261ab6e067e
Revises: ef447cb36f4a
Create Date: 2018-08-07 21:17:27.817947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4261ab6e067e'
down_revision = 'ef447cb36f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_report', sa.Column('next_week_todo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_report', 'next_week_todo')
    # ### end Alembic commands ###
