"""update for chandao

Revision ID: 7663b5f9c499
Revises: 4036285de0f7
Create Date: 2018-07-30 14:12:55.910632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7663b5f9c499'
down_revision = '4036285de0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chandao_session_id', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('chandao_za', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chandao_za')
    op.drop_column('user', 'chandao_session_id')
    # ### end Alembic commands ###
