"""group logic

Revision ID: 933074590c57
Revises: f82737758885
Create Date: 2018-09-10 20:09:30.710790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933074590c57'
down_revision = 'f82737758885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'group')
    # ### end Alembic commands ###
