"""update

Revision ID: 9bb65662e34a
Revises: 1bc89d5f8079
Create Date: 2018-08-01 17:27:44.986498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb65662e34a'
down_revision = '1bc89d5f8079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chandao_name', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('chandao_password', sa.String(length=40), nullable=True))
    op.drop_column('user', 'chandao_session_id')
    op.drop_column('user', 'chandao_za')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chandao_za', sa.VARCHAR(length=40), nullable=True))
    op.add_column('user', sa.Column('chandao_session_id', sa.VARCHAR(length=40), nullable=True))
    op.drop_column('user', 'chandao_password')
    op.drop_column('user', 'chandao_name')
    # ### end Alembic commands ###
