"""airplane mode 

Revision ID: bad8b1b439ae
Revises: 933074590c57
Create Date: 2018-09-11 16:49:38.158098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad8b1b439ae'
down_revision = '933074590c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('airplane_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'airplane_mode')
    # ### end Alembic commands ###
