"""add report mail title and desc

Revision ID: f82737758885
Revises: 4261ab6e067e
Create Date: 2018-08-08 15:50:13.952900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82737758885'
down_revision = '4261ab6e067e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_report', sa.Column('description', sa.String(length=40), nullable=True))
    op.add_column('weekly_report', sa.Column('project_title', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_report', 'project_title')
    op.drop_column('weekly_report', 'description')
    # ### end Alembic commands ###
